-- Barba Maestra · agenda (ejecuta esto en el editor SQL de tu proyecto Supabase)
-- Cada proyecto de cliente usa SU PROPIO proyecto Supabase (nada se comparte).

create table public.reservas (
  id bigint generated by default as identity primary key,
  nombre text not null default '',
  servicio text not null default '',
  fecha text not null,             -- formato YYYY-MM-DD
  hora text not null,              -- formato HH:MM
  estado text not null default 'pendiente', -- 'pendiente' | 'cancelada'
  notify text not null default '', -- correo del dueño (aviso al reservarse)
  creado_en timestamptz not null default now()
);

alter table public.reservas enable row level security;

-- la página puede leer las reservas para calcular lugares libres
create policy "ver_reservas" on public.reservas for select using (true);

-- la página puede registrar una reserva con el toque
create policy "crear_reservas" on public.reservas for insert with check (true);

-- para proyectos ya existentes: solo agrega la columna del aviso
-- alter table public.reservas add column if not exists notify text not null default '';

-- Uso diario del dueño:
--   cancelar:  update public.reservas set estado='cancelada' where id = <id>;
--   ver todas: select * from public.reservas order by fecha, hora;